news.view.templateRootPath: 'EXT:news/Resources/Private/Templates/Styles/ThemeCamino/Templates/'
news.view.partialRootPath: 'EXT:news/Resources/Private/Templates/Styles/ThemeCamino/Partials/'
news.view.layoutRootPath: 'EXT:news/Resources/Private/Templates/Styles/ThemeCamino/Layouts/'